name: Deploy to developer portal

#on:
#  release:
#    types: [ created ]
#    branches:
#      - main
#      - master

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_IMAGE: keboola-component
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --tag=$APP_IMAGE
      - name: Run Flake Lint
        run: docker run $APP_IMAGE flake8 /code/ --config=/code/flake8.cfg
      - name: Unit Test
        run: docker run $APP_IMAGE python -m unittest discover
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          docker pull quay.io/keboola/developer-portal-cli-v2:latest
          chmod +x ./scripts/update_dev_portal_properties.sh
          chmod +x ./deploy.sh
      - name: Run scripts
        run: |
          ./scripts/update_dev_portal_properties.sh
          ./deploy.sh