name: Deploy to developer portal

on:
  release:
    types: [ created ]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test
        uses: ./.github/actions/build_n_test
      - name: Deploy
        run: |
          docker pull quay.io/keboola/developer-portal-cli-v2:latest
          chmod +x ./scripts/update_dev_portal_properties.sh
          chmod +x ./deploy.sh
      - name: Run scripts
        run: |
          ./scripts/update_dev_portal_properties.sh
          ./deploy.sh